### ISSUE TITLE
Error building in Jenkins pipeline

### ISSUE THREAD

**Issue by richard3d** [opensensorhub/osh-js#36]
It seems gulp-css-clean is having an issue processing imports along the way. Here is full stack trace:
`[15:33:02] Finished 'build' after 2.94 μs
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Ignoring local @import of "font-awesome-4.6.3/css/font-awesome.min.css" as resource is missing. Ignoring local @import of "font-awesome-4.6.3/css/font-awesome.min.css" as resource is missing. Ignoring local @import of "font-awesome-4.6.3/css/font-awesome.min.css" as resource is missing. Ignoring local @import of "font-awesome-4.6.3/css/font-awesome.min.css" as resource is missing.)
    at DestroyableTransform.emit (events.js:163:17)
    at DestroyableTransform.onerror (/jslave/workspace/VeniceGeo/osh-js/osh-js-pipeline/Toolkit/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at onwriteError (/jslave/workspace/VeniceGeo/osh-js/osh-js-pipeline/Toolkit/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:10)
    at onwrite (/jslave/workspace/VeniceGeo/osh-js/osh-js-pipeline/Toolkit/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:373:11)
    at WritableState.onwrite (/jslave/workspace/VeniceGeo/osh-js/osh-js-pipeline/Toolkit/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:126:5)
    at afterTransform (/jslave/workspace/VeniceGeo/osh-js/osh-js-pipeline/Toolkit/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:81:3)
    at TransformState.afterTransform (/jslave/workspace/VeniceGeo/osh-js/osh-js-pipeline/Toolkit/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at /jslave/workspace/VeniceGeo/osh-js/osh-js-pipeline/Toolkit/node_modules/gulp-clean-css/index.js:33:16`

**Comment by richard3d** [comment]
The semver in package.json for gulp-clean-css was asking for anything above 2.0.12. For some reason local installation brought 2.3.2, however Jenkins somehow was getting 2.4.0 which was causing the break. I updated package.json to force the version to 2.3.2 and everything works (I currently have Jenkins pointing to unit_tests branch).
