### ISSUE TITLE
[FFMpeg] WebWorker concurrent error

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-js#66]
If we try to load the same dataSource into different FFMPeg view, we get an error:
```
Uncaught DOMException: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already neutered.
    at BaseClass.decodeWorker (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/ui/view/video/osh-UI-FFMPEGView.js:307:21)
    at BaseClass.setData (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/ui/view/video/osh-UI-FFMPEGView.js:118:18)
    at BaseClass.<anonymous> (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/ui/view/osh-UI-View.js:111:26)
    at BaseClass.fire (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/osh-MapEvent.js:41:33)
    at Function.OSH.EventManager.fire (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/osh-EventManager.js:32:14)
    at BaseClass.dispatchData (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/osh-Buffer.js:361:26)
    at BaseClass.processData (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/osh-Buffer.js:336:12)
    at BaseClass.push (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/osh-Buffer.js:250:12)
    at BaseClass.<anonymous> (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/datareceiver/osh-DataReceiverController.js:199:25)
    at BaseClass.onMessage (http://shirow-xeon/progs-local/osh-js/Toolkit/src/osh/datareceiver/osh-DataReceiver-DataSource.js:112:10)
```

**Comment by mdhsl** [comment]
This is cause by the transferable data. 
The transferableData actually transfers the ownership of the object to or from the web worker.
It's like passing by reference where a copy isn't made. The difference between it and the normal pass-by-reference is that the side that transferred the data can no longer access it. In that case, the use of the data must be UNIQUE, that means  you cannot use the data for anything else (like another viewer).

The non transferable data is a copy of the data to be made before being sent to the worker. That could be slow for a large amount of data.

You can now use a properties "useWebWorkerTransferableData" to specify if you want to use transferable or not. If the case where the data is only used in one view, it's better to use it, otherwise, don't. Note that the "useWebWorkerTransferableData" is set to FALSE by default. This is to be sure in the most of case it will work and the "useWebWorkerTransferableData" allows only to speed up the transfert, for more advanced users.
