### ISSUE TITLE
Error in DrawLayer Showcase

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-js#83]
Occasionally getting this error when running the DrawLayer Showcase example at http://opensensorhub.github.io/osh-js/Showcase/#/ :

An error occurred while rendering. Rendering has stopped.
DeveloperError: renderState.lineWidth is out of range.  Check minimumAliasedLineWidth and maximumAliasedLineWidth.
Error
    at new DeveloperError (http://opensensorhub.github.io/osh-js/Showcase/vendor/vendor-debug.js:1327:19)
    at new RenderState (http://opensensorhub.github.io/osh-js/Showcase/vendor/vendor-debug.js:71737:23)
    at Function.RenderState.fromCache (http://opensensorhub.github.io/osh-js/Showcase/vendor/vendor-debug.js:71966:22)
    at createRenderStates (http://opensensorhub.github.io/osh-js/Showcase/vendor/vendor-debug.js:82559:50)
    at Primitive.update (http://opensensorhub.github.io/osh-js/Showcase/vendor/vendor-debug.js:82906:13)
    at _.update (http://opensensorhub.github.io/osh-js/Toolkit/vendor-local/cesium-draw-helper/DrawHelper.js:325:58)
    at PrimitiveCollection.update (http://opensensorhub.github.io/osh-js/Showcase/vendor/vendor-debug.js:165367:27)
    at updatePrimitives (http://opensensorhub.github.io/osh-js/Showcase/vendor/vendor-debug.js:173861:27)
    at executeCommandsInViewport (http://opensensorhub.github.io/osh-js/Showcase/vendor/vendor-debug.js:173748:13)
    at updateAndExecuteCommands (http://opensensorhub.github.io/osh-js/Showcase/vendor/vendor-debug.js:173613:17)

**Comment by mikebotts** [comment]
Might be related to straight line drawn across center of the US (?). Shows artifacts with certain zoom levels, etc:

![screen shot 2017-08-15 at 11 32 00 am](https://user-images.githubusercontent.com/7469574/29325525-a0e882d6-81ad-11e7-835d-b1bfdb88f9be.jpg)

![screen shot 2017-08-15 at 11 32 19 am](https://user-images.githubusercontent.com/7469574/29325534-a8505e9a-81ad-11e7-9eb3-b667aba60e26.jpg)
